import Head from 'next/head'
import MainContainer from '../components/MainContainer'

export default function Home() {
  return (
    <div className='bg-[#1E2630] h-screen'>
      <Head>
        <title>Evolv Fit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <MainContainer />

    </div>
  )
}
